name: Next Js CI Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.x

      - name: Install Bun
        run: npm install -g bun

      - name: Check Bun version
        run: bun --version

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build
        env:
          NODE_ENV: production
          BUN_INSTALL: /home/runner/.bun
